### ISSUE TITLE
Problem installing sujit-baniya/log on go v 17.6

### ISSUE THREAD

**Issue by nordbit** [sujit-baniya/fiber-boilerplate#24]
I got an error while installation

```
$ go get .
# github.com/sujit-baniya/fiber-boilerplate
github.com/sujit-baniya/log.(*Logger).header: relocation target runtime.walltime not defined
```

linux x64 go version 17.6

**Comment by sujit-baniya** [comment]
Hi @nordbit,

Thank you for trying the package and reporting the issue. The issue is due to libraries not being updated. I've updated dependencies.

Please pull latest master and let me know if it works

**Comment by nordbit** [comment]
Yes, it works now. Thank You
