### ISSUE TITLE
sblogger not found

### ISSUE THREAD

**Issue by 0xbs0d** [sujit-baniya/fiber-boilerplate#31]
Hi, I wanted to try this but during the setup it says the sblogger repo cannot be found. Searching through your repos it seems that it has been removed. Any help? Thank you.

**Comment by sujit-baniya** [comment]
@0xbs0d Sorry about that. Let me check and fix it quickly

**Comment by sujit-baniya** [comment]
I've pushed the fixes and updated the dependencies as well. It's quite long I've not worked on this boilerplate. Please let me know if you need further support on this boilerplate

**Comment by adderbyte** [comment]
v1.2.1 still gives the error, `sblogger` required. Dowloading this version and checking it 
`github.com/sujit-baniya/sblogger v0.0.9 
github.com/sujit-baniya/sblogger v0.0.9/go.mod `

is still part of the requirement. I don't want to open new issue since it is still related to this
