### ISSUE TITLE
sblogger still required in latest version

### ISSUE THREAD

**Issue by adderbyte** [sujit-baniya/fiber-boilerplate#34]
It seems the sblogger is still required in v1.2.1. Perhaps a new version can be released from an updated version.

`go: github.com/sujit-baniya/fiber-boilerplate@v1.2.1 requires
	github.com/sujit-baniya/sblogger@v0.0.9: reading github.com/sujit-baniya/sblogger/go.mod at revision v0.0.9: git ls-remote`

**Comment by sujit-baniya** [comment]
@adderbyte Fixed in https://github.com/sujit-baniya/fiber-boilerplate/releases/tag/v1.2.2
