### ISSUE TITLE
Mysql timezone

### ISSUE THREAD

**Issue by azerturk** [sujit-baniya/fiber-boilerplate#9]
[error] failed to initialize database, got error unknown time zone Localcasbin

I am using mysql i added line to the my.ini default-time-zone = "+04:00" and then i changed the loc in connectionstring but no success

**Comment by sujit-baniya** [comment]
Thank you for opening Issue!

The issue was on Casbin Implementation. I've fixed the issue. Please pull latest code and try again.

Thanks

**Comment by azerturk** [comment]
i tested it again. Error was gone. I set migration true and  migrated it and also i sucessefully registered but email confirmation is not sended and also redirected to the blank page "/do/register" and also after login "/do/login"  then i tested the reset password it works mail is sended but after i clicked mail then submit reset form new error is
"go/src/fiber-boilerplate/models/register.go:35" 
Error 1103: Incorrect table name ''

**Comment by azerturk** [comment]
Okay. I tested a little. The only problem i seen that after logout then reset password mail is not sended  - "use of closed connection".

**Comment by azerturk** [comment]
And also in "config/headers.go" this line "c.Set("X-Content-Type-Options", "nosniff")" causes refused running scripts on browser and you should also update readme file rabbitmq lines part )
Last one i tested when i clikcked the paypal button then in browser console shows error - "SyntaxError: Unexpected token < in JSON at position 0"

**Comment by sujit-baniya** [comment]
@azerturk Yes I'll update both as soon as I'm free
